# Generated by Django 3.1.7 on 2021-03-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touq_app', '0004_employment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='user',
        ),
    ]
